// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger Petstore
//
//  A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
//  Terms Of Service:
//    http://helloreverb.com/terms/
//  Schemes:
//    http
//  Host: localhost:8344
//  BasePath: /apis/v1/petstore
//  Version: 1.0.0
//  License: MIT
//  Contact: Wordnik API Team
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/html
//    - application/json
//    - application/xml
//    - text/xml
//
// swagger:meta
package restapi
