// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindPetsHandlerFunc turns a function with the right signature into a find pets handler
type FindPetsHandlerFunc func(FindPetsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindPetsHandlerFunc) Handle(params FindPetsParams) middleware.Responder {
	return fn(params)
}

// FindPetsHandler interface for that can handle valid find pets params
type FindPetsHandler interface {
	Handle(FindPetsParams) middleware.Responder
}

// NewFindPets creates a new http.Handler for the find pets operation
func NewFindPets(ctx *middleware.Context, handler FindPetsHandler) *FindPets {
	return &FindPets{Context: ctx, Handler: handler}
}

/* FindPets swagger:route GET /pets findPets

Returns all pets from the system that the user has access to

*/
type FindPets struct {
	Context *middleware.Context
	Handler FindPetsHandler
}

func (o *FindPets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFindPetsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
